type_name:
  allowed_symbols: "_"

identifier_name:
  allowed_symbols: "_"
  min_length: # only min_length
    warning: 0 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

disabled_rules:
  - line_length